[build-system]
requires = ["setuptools>=46.4.0", "wheel>=0.34.2", "torch>=1.13.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ["py36", "py37", "py38", "py39", "py310"]

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_third_party = ["torch"]

[tool.flake8]
max-line-length = 88
[tool.poetry]
# other poetry parameters...
readme = "README.md"
[tool.mypy]
ignore_missing_imports = true
warn_unused_configs = true
